---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket, Route53, CloudFront'

Parameters:
  DomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
  BucketName:
    Type: String
    Description: Amazon S3 files bucket name
  HostedZoneId:
    Type: String
    Description: Amazon Route53 Hosted Zone Id for DomainName
  CertificateArn:
    Type: String
    Description: Certificate Link

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private 

  S3BucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties: 
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  -  !GetAtt S3Bucket.Arn
                  - "/*"
            Principal:
              CanonicalUser: !Ref "AWS::AccountId"

  myDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
          - DomainName: !Ref DomainName
            Id: s3Bucket
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/'cloudfrony_id' # set your id
          Enabled: true
          Comment: myDistribution
          DefaultRootObject: index.html
          CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          Aliases:
          - !Ref DomainName
          DefaultCacheBehavior:
            AllowedMethods:
            - GET
            - HEAD
            Compress: true
            TargetOriginId: s3Bucket
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: !Ref CertificateArn
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only

  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      # AliasTarget:
      #   HostedZoneId: Z2FDTNDATAQYW2
      #   DNSName: !GetAtt DomainName

Outputs:
  IDCloudFront:
    Value: !GetAtt
      - myDistribution
      - Id
